apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginxp
    image: prashant301k/pacha:v3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  imagePullSecrets:  # if i comment this wont work bcz private registry
     - name: private-reg-key  # if no secrete key created in kubectl -- wont work

  ## create secrets using privatereg.txt 
