apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort  # k get nodes -o wide to get the external ip
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007